-- 轻课 MomentClass V6 Supabase 数据库初始化脚本
-- 使用方法：Supabase → SQL Editor → New query → 粘贴本文件全部内容 → Run

drop table if exists votes cascade;
drop table if exists poll_options cascade;
drop table if exists polls cascade;
drop table if exists students cascade;
drop table if exists users cascade;
drop table if exists course_state cascade;

create table users (
  id bigint generated by default as identity primary key,
  role text not null check (role in ('teacher', 'student')),
  account text not null unique,
  password text not null,
  real_name text not null,
  major_class text default '',
  created_at timestamptz default now()
);

create table students (
  id bigint generated by default as identity primary key,
  account text not null unique,
  real_name text not null,
  major_class text not null,
  signed boolean default false,
  voted boolean default false,
  called boolean default false,
  sign_time text,
  created_at timestamptz default now()
);

create table course_state (
  id bigint primary key,
  class_active boolean default false,
  sign_active boolean default false,
  current_teacher text default '张可',
  updated_at timestamptz default now()
);

create table polls (
  id bigint generated by default as identity primary key,
  question text not null,
  active boolean default true,
  created_at timestamptz default now()
);

create table poll_options (
  id bigint generated by default as identity primary key,
  poll_id bigint references polls(id) on delete cascade,
  option_text text not null,
  sort_order int default 0
);

create table votes (
  id bigint generated by default as identity primary key,
  poll_id bigint references polls(id) on delete cascade,
  option_id bigint references poll_options(id) on delete cascade,
  account text not null,
  created_at timestamptz default now(),
  unique (poll_id, account)
);

insert into users (role, account, password, real_name, major_class) values
('teacher', 'T2026001', '123456', '张可', ''),
('student', '2023123456', '123456', '李静', '2023级新闻班');

insert into students (account, real_name, major_class, signed, voted, called) values
('2023123456', '李静', '2023级新闻班', false, false, false),
('202311001', '李明轩', '2023级广告班', false, false, false),
('202311002', '陈雨桐', '2023级新闻班', false, false, false),
('202311003', '王一诺', '2023级广告班', false, false, false),
('202311004', '赵嘉禾', '2023级新闻班', false, false, false),
('202311005', '周安然', '2023级广告班', false, false, false);

insert into course_state (id, class_active, sign_active, current_teacher)
values (1, false, false, '张可');

-- 课程作业演示版：关闭 RLS，允许前端 anon key 直接读写。
-- 正式上线时不建议这样做，应改用 Supabase Auth + RLS 策略。
alter table users disable row level security;
alter table students disable row level security;
alter table course_state disable row level security;
alter table polls disable row level security;
alter table poll_options disable row level security;
alter table votes disable row level security;

grant usage on schema public to anon, authenticated;
grant all on all tables in schema public to anon, authenticated;
grant all on all sequences in schema public to anon, authenticated;
